apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: application
  name: application
spec:
  replicas: 2
  selector:
    matchLabels:
      service: application
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        network/db-net: "true"
        service: application
    spec:
      containers:
        - args:
            - python3
            - app.py
          image: feyerina/app
          name: application
          ports:
            - containerPort: 8000
          imagePullPolicy: IfNotPresent
          resources: {}
          volumeMounts:
            - mountPath: /logs
              name: application-claim0
      restartPolicy: Always
      volumes:
        - name: application-claim0
          persistentVolumeClaim:
            claimName: application-claim0
status: {}
