apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: application
  name: application
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    service: application
status:
  loadBalancer: {}
